version: '3.3'
services:
  application:
    image: quarantine_code:0.0.1
    container_name: quarantine_code
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/quarantine_code_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12-alpine
    container_name: quarantine_code-postgres
    environment:
      - POSTGRES_DB=quarantine_code_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - quarantine_code_psql:/var/lib/postgresql/data
volumes:
  quarantine_code_psql:
